// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://esggsqfadxkdxtzqwccf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzZ2dzcWZhZHhrZHh0enF3Y2NmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MTQxODMsImV4cCI6MjA2NTM5MDE4M30.WO852QW-Ws97F8kysSIxSeCL0GTV2lRxo-P1M0yacE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);